name: web-push-service

services:
  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  mongo:
    image: mongo:latest
    ports:
      - ${MONGO_PORT:-27017}:27017
    healthcheck:
      test: "echo 'db.runCommand({ ping: 1 })' | mongosh localhost:27017/web_push --quiet"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
